version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: sh -c "yarn install && yarn run dev"
    ports:
      - "3000:3000"
    env_file:
      - .env
    working_dir: /app
    volumes:
      - ./:/app
    environment:
      MYSQL_HOST: ${DB_HOST}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DB: ${DB_NAME}

  mysql:
    image: mysql:8.0
    volumes:
      - todo-mysql-data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"

volumes:

  todo-mysql-data: